
class _int(int):
    def __str__(self) -> str:
        return super().__repr__()
    def __repr__(self) -> str:
        return f"{self.__class__.__name__}({super().__repr__()})"
    
class int8(_int):...
class int16(_int):...
class int24(_int):...
class int32(_int):...
class int40(_int):...
class int48(_int):...
class int64(_int):...
class int72(_int):...
class int80(_int):...
class int96(_int):...
class int104(_int):...
class int112(_int):...
class int128(_int):...
class int160(_int):...
class int192(_int):...
class int216(_int):...
class int224(_int):...
class int256(_int):...
