version: "3.7"

networks:
  evm_contract_exporter:

services:
  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - ${GF_PORT:-3000}:3000
    environment:
      #- GF_PORT
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/yearn/Overview.json
      - GF_SERVER_ROOT_URL
      - GF_RENDERING_SERVER_URL=http://renderer:8091/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
      - GF_INSTALL_PLUGINS=volkovlabs-variable-panel
    command: >
      sh -c "grafana-cli plugins install frser-sqlite-datasource && /run.sh"
    volumes:
      - ~/.evm_contract_exporter/:/var/lib/evm_contract_exporter
      - ~/.evm_contract_exporter/grafana/data/:/var/lib/grafana
      - ~/.evm_contract_exporter/grafana/provisioning/:/etc/grafana/provisioning/
    
    networks:
      - evm_contract_exporter
    restart: always

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 127.0.0.1:${RENDERER_PORT:-8091}:8091
    environment:
      - ENABLE_METRICS=true
      - HTTP_PORT=8091
    networks:
      - evm_contract_exporter
    restart: always